apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: airflow
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
