apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.global.db.password }}"
  JWT_SECRET_KEY: "{{ .Values.global.jwtSecret }}"
